name: Deploy Multi
on:
  push:
    branches:
      - master
   # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - 
        name: Checkout
        uses: actions/checkout@v2
      -
        name: docker login action
        uses: docker/login-action@v2
        with:
          username: ${{ vars.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
#      - 
#        name: docker login
#        run: docker login -u ${{ vars.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: docker build client for test
        run: docker build -t graljo/multi-client-test -f ./client/Dockerfile.dev ./client
      -
        name: docker run client test
        run: docker run -e CI=true graljo/multi-client-test npm test

      - name: Build and push all for deploy
        run: |
          docker build -t graljo/multi-client ./client
          docker build -t graljo/multi-nginx ./nginx
          docker build -t graljo/multi-server ./server
          docker build -t graljo/multi-worker ./worker
          docker push graljo/multi-client
          docker push graljo/multi-nginx
          docker push graljo/multi-server
          docker push graljo/multi-worker

#      - name: Generate deployment package
#        run: zip -r deploy.zip . -x '*.git*'

#      - name: Deploy to EB
#        uses: einaregilsson/beanstalk-deploy@v18
#        with:
#          aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
#          aws_secret_key: "${{ secrets.AWS_SECRET_KEY }}"
#          application_name: "Udemy Docker React"
#          environment_name: Udemydockermulti-env
#          existing_bucket_name: "elasticbeanstalk-us-west-1-565295202784"
#          region: us-west-1
#          version_label: ${{ github.sha }}
#          deployment_package: deploy.zip
